### ISSUE TITLE
Variable "forms" does not exist in "__string_template__...

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/sprout-reports#102]
I'm on Craft 3.4.25, Sprout Reports 1.5.6, and Commerce Data Source for Sprout Reports 1.0.4.

My 'settings' page has the following:

```
{# Number Setting #}
{{ forms.textField({
    label: "Limit"|t,
    name: "limit",
    size: 10,
    value: 1,
    first: true
}) }}
```

Running the report or attempting to change the report settings (e.g. template path, report name etc) gives the error:
Variable "forms" does not exist in "__string_template__...

Initially posted here: https://github.com/barrelstrength/craft-sprout-reports/issues/63#issuecomment-726382284

**Comment by BenParizek** [comment]
@jamiematrix Can you confirm that you are trying to create a Twig Template report?

It would be helpful to clarify that as you mention Commerce Data Source but those are pre-prepared reports where you wouldn't be building your own templates so I just want to make sure that we're talking about the same thing. A screenshot of your current report settings could be helpful.

**Comment by jamiematrix** [comment]
> @jamiematrix Can you confirm that you are trying to create a Twig Template report?
> 
> It would be helpful to clarify that as you mention Commerce Data Source but those are pre-prepared reports where you wouldn't be building your own templates so I just want to make sure that we're talking about the same thing. A screenshot of your current report settings could be helpful.

Correct, it is a Twig Template report I'm trying to create.
I only mentioned that Commerce Data Source plugin was in there (enabled) because if it's not enabled then I get an error of
`Unable to locate message source for category 'sprout-reports-commerce`

**Comment by BenParizek** [comment]
Ok. Good to know. Sounds like we have a translation category issue too. I'll look into addressing that afterwards.

You should be able to solve this by importing the form macros at the top of your settings template:

```
{% import '_includes/forms' as forms %}

{# Number Setting #}
{{ forms.textField({
    label: "Limit"|t,
    name: "limit",
    size: 10,
    value: 1,
    first: true
}) }}
```

I might still be missing something here that changed, so I'll dig into this a bit more and follow up on this thread and update the docs once I do.

**Comment by jamiematrix** [comment]
Thanks! That import seems to have done the trick for getting the settings loaded.

I presumed the category error was due to Craft Commerce being installed, but the data source plugin not being enabled.
