### ISSUE TITLE
Using macro in addRow adds whitespace when exporting

### ISSUE THREAD

**Issue by jamiematrix** [barrelstrength/sprout-reports#107]
### Description (screenshots, logs, ...)
I'm using a macro to prepend a £ and show 2 decimal places to certain columns to show a currency value. If I use that macro it adds whitespace to the value along with the character 'Â' before the the actual value. This makes the columns look empty in Excel, but they have an extra line pushing the value out of view.

The macro is:
```
{% macro CurrencySym(input) %}
    {% set input = input|number_format(2) %}
    £{{ input|replace(".00", "")}}
{% endmacro %}
```

The output is fine when viewing the report within admin, but exporting adds the whitespace. Even have the macro just output the value that is parsed in still adds the whitespace.

### Steps to reproduce

1. Add a simple macro to the template
2. Export report and see columns that use the macro are blank until the row is expanded.

### Additional info

- Craft version: 3.4.25
- PHP version: 7.3.7
- Database driver & version:  MySQL 5.7.24
- Plugins & versions: Sprout Reports 1.5.6, Craft Commerce 3.1.10, Commerce Data Source for Sprout Reports 1.0.4

**Comment by BenParizek** [comment]
@jamiematrix If you need different behavior with the output in the UI and within the CSV, we do have an `isExport` variable:
https://sprout.barrelstrengthdesign.com/docs/reports/html-vs-csv-reports.html

You might also want to strip whitespace from your macro using dashes within your macro tags or the spaceless variable:
https://twig.symfony.com/doc/3.x/templates.html#whitespace-control
https://twig.symfony.com/doc/2.x/tags/spaceless.html

I don't have a quick answer regarding the `Â` character in the export. This could be an encoding-related issue somewhere in the workflow and may not relate to the plugin export behavior. For example, they can relate to the settings you use when you import a CSV into Excel. So it might be worth trying to import it into Google Spreadsheets too to see if the encoding issue is always present or just present in a single workflow.

Let me know if the above can help resolve some of those issues. If not, I can take a deeper look as to what might be going on and I might need more time to dig into anything encoding-related issues if that persists.
