### ISSUE TITLE
Ocassional Wrong URL for "Run Report" link

### ISSUE THREAD

**Issue by GaryReckard** [barrelstrength/sprout-reports#112]
### Description (screenshots, logs, ...)
I haven't determine the exact steps to reproduce this issue, but it happens somewhat frequently that when I click on the "Run Report" button, I end up on a "Page Not Found"
![image](https://user-images.githubusercontent.com/1679951/113200919-ebfc4580-9236-11eb-8e18-fe909b7a8b41.png)

For some reason, when on the Reports list page, the link for "Run Report" ends up being `/admin/sprout-reports/view/2748788` rather than the correct `/admin/sprout-reports/reports/view/2748788`. (missing the /reports/ part)

### Additional info

- Craft version: 3.4.25
- PHP version: 7.3
- Database driver & version:   MySQL 5.7.28
- Plugins & versions: Sprout Reports 1.5.6

**Comment by BenParizek** [comment]
@GaryReckard It appears you are an older version of are plugin and we may have addressed this in a more recent version if want to try to update to v1.5.10

Broadly speaking, I believe this stems from a deeper issue we have in our plugins right now that I'm working on fixing in the next major release. A while back I made a decision to break out some shared functionality to several composer modules which has subsequently lead to a handful of issues with migrations and permissions between the shared modules. The underlying issue that lead to this will be removed in the next major release, which currently has my focus.

**Comment by jamesmacwhite** [comment]
I've hit this as well and I'm running the latest version, so it still seems to be present?

**Comment by BenParizek** [comment]
This issue has been resolved in Sprout Data Studio (previously Sprout Reports) for Craft 4:
https://plugins.craftcms.com/sprout-data-studio
