### ISSUE TITLE
Settings are not compatible with Project Config

### ISSUE THREAD

**Issue by thisisjamessmith** [barrelstrength/sprout-reports#116]
### Description

Updating Sprout Reports' settings in the control panel doesn't alter the Project Config settings, and when administrative changes are disabled on the remote it's not possible to access the Sprout Reports settings area directly in the control panel.

### Additional info

- Craft version: 3.7
- Plugin version: 1.5.12

**Comment by BenParizek** [comment]
Project Config support for Sprout settings has been added in Sprout Data Studio (previously Sprout Reports) for Craft 4:
https://plugins.craftcms.com/sprout-data-studio
