### ISSUE TITLE
Craft 4 Support

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/sprout-reports#124]
Sprout Reports is in the process of being updated to Craft 4. Please see the statement in our docs for additional details:
https://sprout.barrelstrengthdesign.com/docs/support/road-map.html

Follow this thread if you'd like to be notified when the upgrade is ready.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_4p77x)

**Comment by bboy-splendid** [comment]
Any news of a date when this might be available? This is the only outstanding plugin for a project we are waiting on to move forwards to Craft 4 now. Many thanks!

**Comment by iamkeir** [comment]
@splendidrob and it really is an _outstanding_ plugin too! :)

**Comment by BenParizek** [comment]
While it's going to take a bit longer, I'm actively working on updating all the plugins listed in the Road Map above to Craft 4, and Sprout Reports is at the top of the list and should be the first one to be released. I'm not promising any dates yet, but I've gotten through a lot of the blockers that were present in my life that have delayed this to this point and am slowing catching up on my backlog to get this released.

**Comment by markhuot** [comment]
Is Sprout Supports still planned for Craft 4? We have a site that is waiting for this plugin before upgrading.

**Comment by danielsiemers** [comment]
Hey there great news that this is in it's final stages! Is there any news of a date when this might be available? Cheers

**Comment by BenParizek** [comment]
Short update. Sprout Reports will be renamed to Sprout Data Studio for Craft 4 and I'm working through the process of getting the new plugin into the plugin store. If all goes smoothly there, I expect I'll be able to have this out by next week and will update this thread once I do.

**Comment by markhuot** [comment]
Yay! Thanks for the update @BenParizek. I can't wait to see the _new_ Sprout Data Studio.

**Comment by BenParizek** [comment]
Hi All. I've just tagged Sprout Data Studio v4.44.444 which adds Craft 4 support. I'm still sorting out the license migration, so that may take another couple of days, but expect all Sprout Reports licenses to be migrated to Data Studio Pro licenses. I'll update this thread once the license migration is complete.

While the core functionality remains the same, there are several breaking changes, especially if you are using Custom Data Sources or the Twig Query Data Set so please see the [upgrade guide](https://sprout.barrelstrengthdesign.com/docs/craft-v4/updates/4.44.444-data-studio.html) or open a ticket if you have any questions.

**Comment by hatzipanis** [comment]
Hi @BenParizek, any update here? Not to put any pressure on but this is currently holding us back from deploying Craft 4 for one of our clients 😄. Thanks for all your efforts to get this done.

**Comment by BenParizek** [comment]
@hatzipanis I'll be sending out a notification to all license holders shortly but licenses for Data Studio have been created in the Craft Console account that matches the email address the Sprout Reports license was purchased under. Let me know if you don't see it or send a note to sprout@barrelstrengthdesign.com with details on your situation and we can sort it out.

**Comment by BenParizek** [comment]
To summarize the above before I close this out:

[Data Studio](https://plugins.craftcms.com/sprout-data-studio) has been released. Upgrade notes can be found [here](https://sprout.barrelstrengthdesign.com/docs/craft-v4/updates/4.44.444-data-studio.html).

All Sprout Reports license holders have been notified and a new license for Sprout Data Studio Pro has been created in the the Craft Console account with the same email where they held their Sprout Reports license.

I'm closing this out and shutting down the Issues tab on this repository. Future support and Q&A for Reports, Data Studio, and all of our plugins will be handled out of the [main Sprout repository](https://github.com/barrelstrength/sprout) and will be noted in the README file for this repo.
