### ISSUE TITLE
Settings not available/showing up in Results

### ISSUE THREAD

**Issue by Coalescent** [barrelstrength/sprout-reports#73]
### Description (screenshots, logs, ...)
I am trying to use settings on some reports but they never show up on the report's result page in the CP. Getting frustrated, I used the User Report example templates, with no edits, and found the same behaviour - no settings showing up (and no errors).

I then tried to output something from the settings in Results: `{{ settings.limitByDateRange }}`

And that produced this error:

`Key "limitByDateRange" for array with keys "resultsTemplate, settingsTemplate" does not exist.`

So, for some reason, it seems nothing in the settings file is available in the results file.

### Steps to reproduce

1. Install latest Reports plugin
2. Install latest Craft
3. Set up a report using the `activeusersreport` files
4. View report in the CP and see no settings appearing

### Additional info

- Craft version: Craft Pro 3.3.19
- PHP version: 7.3.8
- Database driver & version:  MySQL 5.7.26
- Plugins & versions:

Abandoned Cart for Craft Commerce 2	1.3.6
Cookies	1.1.11
Craft Commerce	2.2.13
Feed Me	4.2.0
Field Labels	1.1.8
Field Manager	2.1.1
Freeform	3.5.9
Inventory	2.0.3
Linkit	1.1.11
Link Vault	3.0.5.4
Logout Redirect	2.0.1
Redactor	2.4.0
Smart Map	3.2.2.1
Sprout Email	4.0.6
Sprout Reports	1.2.11
Sprout SEO	4.2.8
Stripe for Craft Commerce	2.2.3
Super Table	2.3.1
Template Comments	1.1.2
Wordsmith	3.1.1

**Comment by BenParizek** [comment]
Thanks for the details. Let me confirm a few more things before we get to the errors on your results page.

It sounds like you copied over the example `results.html` and `settings.html` files into your templates folder. Did you add both of those filepaths to the Twig Template report settings? Once you add those paths you'll need to save the settings and then you should see those additional settings defined in your `settings.html` file appear when editing that report:
https://share.barrelstrength.co/nOumRnK1

The error suggesting that those settings don't exist suggests the settings may not have been saved for the report yet.

Just to be a bit more verbose, the settings file and the results file are not communicating directly with one another. The settings file will make the Twig Template report aware of those new settings and save the values for those settings when you save the Twig Template Report. To allow you to define settings on the front-end like this, we have to require you save that report twice. Once to communicate to the report where the settings file actually exists and the second time once you see the actual settings that the settings file makes available to you. The results template is then also communicating with the Twit Template report by looking at its settings for whatever values you've made available there.

**Comment by Coalescent** [comment]
> It sounds like you copied over the example results.html and settings.html files into your templates folder. 

Yes.

> Did you add both of those filepaths to the Twig Template report settings?

Yes.

> Once you add those paths you'll need to save the settings and then you should see those additional settings defined in your settings.html file appear when editing that report:

I did that and regardless of how many times I save the report, this is what I continue to see (settings not showing up):

![image](https://user-images.githubusercontent.com/6394091/72037750-0d4ccc80-3254-11ea-8c4c-d3b897ca7ca3.png)

This behaviour is the same for my custom reports with settings. Also note that the filepaths are definitely correct (I've rechecked them) and I did try clearing all caches.

**Comment by BenParizek** [comment]
@Coalescent Thanks for confirming. Assuming your results.html and settings.html files have the same content as the example files. It does appear you have things set up correctly, so we'll have to dig into some details to try to figure out what might be going on.

Could you confirm that you have Craft configured to check for both `.html` and `.twig` files? I believe the example files use `.html` so if you happen to have disabled the check for `.html` files and only allow Twig that would affect what files Sprout found.

Aside from that, could you do the following to check the exact filepath that Sprout thinks it's loading and see if it's what you expect? In the Custom Twig Template datasource in `vendor/barrelstrength/craft-sprout-reports/src/datasourcees` on line 111 or so:
https://github.com/barrelstrength/craft-sprout-reports/blob/v1.2.11/src/datasources/CustomTwigTemplate.php#L111

Can you add the following line after `$customSettingsTemplatePath` is defined:

```
\Craft::dd($customSettingsTemplatePath);
```

Make sure `devMode` is enabled and then reload the settings page and that should output the path that Sprout thinks the settings are. If that is what you expect it to be, you could also test the conditional statement just below that where we check if a file exists with one of the supported file extensions. From what you describe, it sounds like this method is not finding a template to output your settings in the UI so we'll need to figure out why.

**Comment by Coalescent** [comment]
Ok, so that was helpful Ben. I forgot to mention this is a multi-site setup - and that seems to be part of the issue.

When I checked that filepath from your plugin, I got:

`craft/templates/_reports/test-report/settings`

But the actual full path is:

`craft/templates/site_1/_reports/test-report/settings.html`

And as you saw in my screenshot, the Settings page has the template path as:

`_reports/test-report/settings` which is input with Craft's built-in auto-complete where it shows you that path for a specific site (which is why I wouldn't have expected to include `site_1` as part of the path).

If I change the path in Settings to `site_1/_reports/test-report/settings` I now see the fields UI on the Settings page but still _do not_ see that UI on the Results page, so there still seems to be an issue.

I assumed the plugin is multi-site compatible, but maybe not?

**Comment by BenParizek** [comment]
Thanks for the additional clarification @Coalescent 

I think the best solution for this will be to add support for aliases and environment variables for those template settings. I'll update this thread when we get a fix out.

**Comment by bboy-splendid** [comment]
@BenParizek Did this ever get solved? I'm having the exact same issue. Templates copied over and added to the report settings, files defined as .twig. No settings showing whatsoever. There is also nothing at the above filepath anymore (vendor/barrelstrength/craft-sprout-reports/src/datasourcees) which I am assuming has changed due to updates. Any advice as to how to enable settings for custom twig reports?

Judging by @Coalescent issues with a multisite above it is worth mentioning our current setup was multisite for a bit before it was removed and set back to a single site so there could be some hangover issues?

**Comment by BenParizek** [comment]
@bboy-splendid At some point we updated to use the new Craft, template select field which includes the file extension when you select the templates (.twig, .html) but the underlying code assumes that that setting does not include the extension and tries to add it in so it ends up with '.twig.twig' or '.twig.html'). I'll add this to my list to get corrected, but for now, you should just be able to remove '.twig' from your selection and get those settings working.

**Comment by bboy-splendid** [comment]
@BenParizek Yep that solved it, many thanks!

**Comment by BenParizek** [comment]
The underlying issue here is resolved when migrating to Sprout Data Studio for Craft 4.
