### ISSUE TITLE
CSV export with line-breaks

### ISSUE THREAD

**Issue by SamLNL** [barrelstrength/sprout-reports#89]
### Description
I've a form with a 'paragraph'-field. I'm using this field for 'comments' so this form-data often includes line-breaks.

Because of these line-breaks, the export of this form (CSV-file) also has those line-breaks and makes it unreadable. Especially when converting this CSV-file to excel-columns.

### Steps to reproduce

1. Add 'paragraph' field to form
2. Submit form using line-breaks in the paragraph field
3. Export to CSV
4. Convert CSV in excel to columns (optional)

### Additional info

- Craft version: Craft CMS 3.1.7
- PHP version: 7.0.32
- Database driver & version: MySQL 5.5.52
- Plugins & versions: Sprout Forms 3.0.0-beta.38

**Comment by BenParizek** [comment]
@jeffreyschmitz87 Can you share more about your workflow? We currently believe this may have to do with a step you are taking when importing the data into Excel.

In our tests, importing an exported comma-delimited file worked fine in Excel on Windows. However, using the "From Text" or "Paste as Text" options lead to different results.

In the case this might be an encoding issue, you can check the encoding of the exported file in the following way:

To see which encoding your export is using, you can go to the export page and open Dev Tools in your browser. Click on the Network tab and check the setting "Preserve log" (which will make sure the export request stays in the list after it is complete).

Run your export, and when you see your export request appear in the Network tab, click on it and look in the Headers -> Response Headers section for the "content-type" value.
https://share.barrelstrength.co/jkulRw0J

The default content-type should be: content-type: text/csv;charset=UTF-8

Let me know what you find.

**Comment by jeffreyschmitz87** [comment]
@BenParizek This is my workflow:
1) Double click on the exported CSV - file
2) Select the first column (`A`)
2) Go to the `Data` tab and click the `Text To Columns` option and select `Separated` (see `csv-1.jpg`)
3) In the next step click the `Comma` option (see `csv-2.jpg`).

This will result in the provided image in my [first comment](#issuecomment-627235691)

**Files**
- ![csv-1](https://user-images.githubusercontent.com/34717885/81786751-5feb0d80-9500-11ea-877f-b070468e13f1.jpg)
- ![csv-2](https://user-images.githubusercontent.com/34717885/81786757-61b4d100-9500-11ea-94d9-7a77ce5338ce.jpg)

`The default content-type should be: content-type: text/csv;charset=UTF-8`
I've exported the report and preserved the log. The Content-Type header is set correct.

**Comment by jeffreyschmitz87** [comment]
@BenParizek 

I've tried one more option opening the CSV - file and this seems to work:
1) Create a new blank file in Excel
2) Go to `Data` > `From Text/CSV`
3) Select the CSV - file and click on `Import`
4) In the next window check if the`Delimiter` option is set to the correct (in this case `Comma separated)
5) Click `Load`

Image below contains the imported data. All of the data containing multines are imported as single lines. The `userAgent` column also doesn't break the row at this point. 

Note: I've edited the image to remove customer data.

![csv-imported](https://user-images.githubusercontent.com/34717885/81787776-d89e9980-9501-11ea-95c8-accbbb775ab7.jpg)

**Comment by jeffreyschmitz87** [comment]
@BenParizek 

A colleague tried importing the CSV - file in Excel on a Mac with the above steps. Importing the data this way doesn't seem to work. I do think this is a Mac Excel problem since importing the CSV - file on another OS/Numbers works fine.

Image below shows the imported data.

**Files**
![csv-import](https://user-images.githubusercontent.com/34717885/81792566-81e88e00-9508-11ea-9522-dba8cd42c1c0.jpg)

**Comment by BenParizek** [comment]
@jeffreyschmitz87 Thanks for the additional details. I'll review this a bit more when I have a chance and see if I can't come up with a more cross-platform solution. This SE post seems to discuss the issue we might be seeing here:

https://stackoverflow.com/a/16766198/1586560

**Comment by BenParizek** [comment]
A delayed mention here but a fix was pushed for Unicode support in v1.5.14 which should help with some Excel scenarios.

I'm going to close this out but please re-open if issues persist. Now that Sprout Reports has migrated to Craft 4 as Sprout Data Studio I can start to revisit some of these issues if they persist.
